"""The committed SQL in ``sql/`` must be what the builder currently emits.

Those files exist so the feature definitions can be read and handed to a data engineer without
running any Python. A committed artefact that has silently drifted from the code is worse than no
artefact, so the check is a test rather than a convention.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from deliveryrisk.data.schema import schema_ddl
from deliveryrisk.features.sql import (
    ENTITIES,
    ORDER_FACTS_SQL,
    build_entity_sql,
    build_events_sql,
    build_features_sql,
)

SQL_DIR = Path(__file__).resolve().parents[1] / "sql"
HEADER = [
    "-- Generated by `drisk features configs/headline.yaml --show-sql`. Committed so the feature",
    "-- definitions can be read, reviewed and scheduled without running any Python.",
    "-- Regenerate with `make sql`; tests/test_sql_artifacts.py fails if this file drifts.",
]


def test_feature_sql_avoids_syntax_mysql_does_not_have():
    """The feature SQL is one dialect for both engines, so it may not use SQLite-only forms.

    `CREATE INDEX IF NOT EXISTS` is the trap: valid on SQLite, a syntax error on MySQL 8, and
    invisible until a real server rejects it. Every table these indexes sit on is dropped
    immediately before it is rebuilt, so the guard was never doing anything anyway.
    """
    sql = "\n".join(
        [
            ORDER_FACTS_SQL,
            build_events_sql(trailing_days=30.0),
            *[build_entity_sql(spec) for spec in ENTITIES],
            build_features_sql(),
        ]
    )
    assert "CREATE INDEX IF NOT EXISTS" not in sql.upper()
    # Each index is on a table this script has just dropped and rebuilt.
    for line in sql.splitlines():
        if line.strip().upper().startswith("CREATE INDEX"):
            table = line.split(" ON ")[1].split("(")[0].strip()
            assert f"DROP TABLE IF EXISTS {table}" in sql, table


@pytest.mark.parametrize("dialect", ["sqlite", "mysql"])
def test_committed_schema_matches_the_generator(dialect):
    path = SQL_DIR / f"schema_{dialect}.sql"
    assert path.exists(), f"{path} is missing; run `make sql`"
    assert path.read_text() == schema_ddl(dialect), f"{path} is stale; run `make sql`"


def test_committed_feature_sql_matches_the_builder():
    parts = [*HEADER, ORDER_FACTS_SQL, build_events_sql(trailing_days=30.0)]
    parts += [
        build_entity_sql(spec, mode="point_in_time", trailing_days=30.0, prior_weight=15.0,
                         prior_rate=0.08)
        for spec in ENTITIES
    ]
    parts.append(build_features_sql(mode="point_in_time"))
    expected = "\n".join(parts) + "\n"
    path = SQL_DIR / "features_point_in_time.sql"
    assert path.exists(), f"{path} is missing; run `make sql`"
    assert path.read_text() == expected, f"{path} is stale; run `make sql`"
