-- Generated by `drisk features configs/headline.yaml --show-sql`. Committed so the feature
-- definitions can be read, reviewed and scheduled without running any Python.
-- Regenerate with `make sql`; tests/test_sql_artifacts.py fails if this file drifts.

DROP TABLE IF EXISTS order_primary;
CREATE TABLE order_primary AS
SELECT order_id, product_id, seller_id, lane_id, shipping_limit_ts
FROM (
    SELECT oi.order_id, oi.product_id, oi.seller_id, oi.lane_id, oi.shipping_limit_ts,
           ROW_NUMBER() OVER (
               PARTITION BY oi.order_id ORDER BY oi.price DESC, oi.item_seq ASC
           ) AS rn
    FROM order_items oi
) t
WHERE rn = 1;

DROP TABLE IF EXISTS order_rollup;
CREATE TABLE order_rollup AS
SELECT oi.order_id,
       COUNT(*)                          AS n_items,
       COUNT(DISTINCT oi.seller_id)      AS n_sellers,
       COUNT(DISTINCT oi.lane_id)        AS n_lanes,
       SUM(oi.price)                     AS total_price,
       SUM(oi.freight_value)             AS total_freight,
       MAX(oi.price)                     AS max_price,
       MIN(oi.shipping_limit_ts)         AS first_shipping_limit_ts,
       SUM(p.weight_g)                   AS total_weight_g,
       MAX(p.weight_g)                   AS max_weight_g,
       MAX(p.length_cm * p.height_cm * p.width_cm) AS max_volume_cm3
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
GROUP BY oi.order_id;

DROP TABLE IF EXISTS order_pay;
CREATE TABLE order_pay AS
SELECT order_id,
       COUNT(*)               AS n_payment_legs,
       SUM(payment_value)     AS payment_total,
       MAX(installments)      AS installments,
       MIN(payment_type)      AS payment_type
FROM order_payments
GROUP BY order_id;

DROP TABLE IF EXISTS order_facts;
CREATE TABLE order_facts AS
SELECT
    o.order_id,
    o.order_status,
    o.purchase_ts,
    o.approved_ts,
    o.pickup_ts,
    o.delivered_ts,
    o.estimated_delivery_ts,
    c.customer_unique_id,
    c.customer_state,
    c.customer_zip_prefix,
    op.seller_id,
    op.lane_id,
    op.product_id,
    op.shipping_limit_ts,
    pr.category,
    s.seller_state,
    s.fulfilment_mode,
    s.onboarded_ts,
    l.carrier_id,
    l.origin_state,
    l.dest_state,
    l.distance_km,
    l.base_transit_days,
    ca.service_level,
    ca.reliability_index,
    ca.expedite_surcharge,
    ca.daily_capacity,
    r.n_items, r.n_sellers, r.n_lanes, r.total_price, r.total_freight, r.max_price,
    r.total_weight_g, r.max_weight_g, r.max_volume_cm3, r.first_shipping_limit_ts,
    pay.n_payment_legs, pay.payment_total, pay.installments, pay.payment_type
FROM orders o
JOIN customers c       ON c.customer_id = o.customer_id
JOIN order_primary op  ON op.order_id = o.order_id
JOIN order_rollup r    ON r.order_id = o.order_id
JOIN products pr       ON pr.product_id = op.product_id
JOIN sellers s         ON s.seller_id = op.seller_id
JOIN shipping_lanes l  ON l.lane_id = op.lane_id
JOIN carriers ca       ON ca.carrier_id = l.carrier_id
LEFT JOIN order_pay pay ON pay.order_id = o.order_id
WHERE o.approved_ts IS NOT NULL;

-- Plain CREATE INDEX, not IF NOT EXISTS: MySQL has no such form, and the table was dropped two
-- statements ago, so the index cannot already exist.
CREATE INDEX ix_order_facts_approved ON order_facts (approved_ts);

DROP TABLE IF EXISTS pit_events;
CREATE TABLE pit_events AS
SELECT 'seller' AS entity_type,
       seller_id AS entity_key,
       approved_ts AS ts,
       0 AS ev_kind,
       approved_ts - 0.0001 AS ev_ts,
       order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       -- The order's own outcome, carried on its decision row. Read by nothing except the
       -- leave-one-out adjustment in `mode="two_sided_loo"`; the point-in-time builder never
       -- touches these columns, and `_assert_no_outcome_features` keeps them out of the model.
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL THEN 1 ELSE 0 END
           AS own_has_outcome,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS own_is_late,
       COALESCE((pickup_ts - approved_ts) / 86400.0, 0.0)   AS own_handling_days,
       COALESCE((delivered_ts - pickup_ts) / 86400.0, 0.0)  AS own_transit_days,
       COALESCE((delivered_ts - estimated_delivery_ts) / 86400.0, 0.0) AS own_days_over,
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
                 AND ABS(delivered_ts - approved_ts) <= 2592000.0 THEN 1 ELSE 0 END
           AS own_in_recent
FROM order_facts
UNION ALL

SELECT 'seller' AS entity_type,
       seller_id AS entity_key,
       delivered_ts AS ts,
       1 AS ev_kind,
       delivered_ts AS ev_ts,
       order_id,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS is_late,
       (delivered_ts - estimated_delivery_ts) / 86400.0 AS days_over,
       (pickup_ts - approved_ts) / 86400.0 AS handling_days,
       (delivered_ts - pickup_ts) / 86400.0 AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts
WHERE delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
UNION ALL

SELECT 'seller' AS entity_type, seller_id AS entity_key, approved_ts AS ts, 2 AS ev_kind,
       approved_ts AS ev_ts, order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       1 AS delta_open,
       approved_ts AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts WHERE approved_ts IS NOT NULL
UNION ALL

SELECT 'seller' AS entity_type, seller_id AS entity_key, COALESCE(pickup_ts, approved_ts + 2592000.0) AS ts, 3 AS ev_kind,
       COALESCE(pickup_ts, approved_ts + 2592000.0) AS ev_ts, order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       -1 AS delta_open,
       -approved_ts AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts WHERE COALESCE(pickup_ts, approved_ts + 2592000.0) IS NOT NULL
UNION ALL

SELECT 'lane' AS entity_type,
       lane_id AS entity_key,
       approved_ts AS ts,
       0 AS ev_kind,
       approved_ts - 0.0001 AS ev_ts,
       order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       -- The order's own outcome, carried on its decision row. Read by nothing except the
       -- leave-one-out adjustment in `mode="two_sided_loo"`; the point-in-time builder never
       -- touches these columns, and `_assert_no_outcome_features` keeps them out of the model.
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL THEN 1 ELSE 0 END
           AS own_has_outcome,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS own_is_late,
       COALESCE((pickup_ts - approved_ts) / 86400.0, 0.0)   AS own_handling_days,
       COALESCE((delivered_ts - pickup_ts) / 86400.0, 0.0)  AS own_transit_days,
       COALESCE((delivered_ts - estimated_delivery_ts) / 86400.0, 0.0) AS own_days_over,
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
                 AND ABS(delivered_ts - approved_ts) <= 2592000.0 THEN 1 ELSE 0 END
           AS own_in_recent
FROM order_facts
UNION ALL

SELECT 'lane' AS entity_type,
       lane_id AS entity_key,
       delivered_ts AS ts,
       1 AS ev_kind,
       delivered_ts AS ev_ts,
       order_id,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS is_late,
       (delivered_ts - estimated_delivery_ts) / 86400.0 AS days_over,
       (pickup_ts - approved_ts) / 86400.0 AS handling_days,
       (delivered_ts - pickup_ts) / 86400.0 AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts
WHERE delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
UNION ALL

SELECT 'lane' AS entity_type, lane_id AS entity_key, pickup_ts AS ts, 2 AS ev_kind,
       pickup_ts AS ev_ts, order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       1 AS delta_open,
       pickup_ts AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts WHERE pickup_ts IS NOT NULL
UNION ALL

SELECT 'lane' AS entity_type, lane_id AS entity_key, delivered_ts AS ts, 3 AS ev_kind,
       delivered_ts AS ev_ts, order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       -1 AS delta_open,
       -pickup_ts AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts WHERE delivered_ts IS NOT NULL
UNION ALL

SELECT 'carrier' AS entity_type,
       carrier_id AS entity_key,
       approved_ts AS ts,
       0 AS ev_kind,
       approved_ts - 0.0001 AS ev_ts,
       order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       -- The order's own outcome, carried on its decision row. Read by nothing except the
       -- leave-one-out adjustment in `mode="two_sided_loo"`; the point-in-time builder never
       -- touches these columns, and `_assert_no_outcome_features` keeps them out of the model.
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL THEN 1 ELSE 0 END
           AS own_has_outcome,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS own_is_late,
       COALESCE((pickup_ts - approved_ts) / 86400.0, 0.0)   AS own_handling_days,
       COALESCE((delivered_ts - pickup_ts) / 86400.0, 0.0)  AS own_transit_days,
       COALESCE((delivered_ts - estimated_delivery_ts) / 86400.0, 0.0) AS own_days_over,
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
                 AND ABS(delivered_ts - approved_ts) <= 2592000.0 THEN 1 ELSE 0 END
           AS own_in_recent
FROM order_facts
UNION ALL

SELECT 'carrier' AS entity_type,
       carrier_id AS entity_key,
       delivered_ts AS ts,
       1 AS ev_kind,
       delivered_ts AS ev_ts,
       order_id,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS is_late,
       (delivered_ts - estimated_delivery_ts) / 86400.0 AS days_over,
       (pickup_ts - approved_ts) / 86400.0 AS handling_days,
       (delivered_ts - pickup_ts) / 86400.0 AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts
WHERE delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
UNION ALL

SELECT 'carrier' AS entity_type, carrier_id AS entity_key, pickup_ts AS ts, 2 AS ev_kind,
       pickup_ts AS ev_ts, order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       1 AS delta_open,
       pickup_ts AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts WHERE pickup_ts IS NOT NULL
UNION ALL

SELECT 'carrier' AS entity_type, carrier_id AS entity_key, delivered_ts AS ts, 3 AS ev_kind,
       delivered_ts AS ev_ts, order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       -1 AS delta_open,
       -pickup_ts AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts WHERE delivered_ts IS NOT NULL
UNION ALL

SELECT 'category' AS entity_type,
       category AS entity_key,
       approved_ts AS ts,
       0 AS ev_kind,
       approved_ts - 0.0001 AS ev_ts,
       order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       -- The order's own outcome, carried on its decision row. Read by nothing except the
       -- leave-one-out adjustment in `mode="two_sided_loo"`; the point-in-time builder never
       -- touches these columns, and `_assert_no_outcome_features` keeps them out of the model.
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL THEN 1 ELSE 0 END
           AS own_has_outcome,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS own_is_late,
       COALESCE((pickup_ts - approved_ts) / 86400.0, 0.0)   AS own_handling_days,
       COALESCE((delivered_ts - pickup_ts) / 86400.0, 0.0)  AS own_transit_days,
       COALESCE((delivered_ts - estimated_delivery_ts) / 86400.0, 0.0) AS own_days_over,
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
                 AND ABS(delivered_ts - approved_ts) <= 2592000.0 THEN 1 ELSE 0 END
           AS own_in_recent
FROM order_facts
UNION ALL

SELECT 'category' AS entity_type,
       category AS entity_key,
       delivered_ts AS ts,
       1 AS ev_kind,
       delivered_ts AS ev_ts,
       order_id,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS is_late,
       (delivered_ts - estimated_delivery_ts) / 86400.0 AS days_over,
       (pickup_ts - approved_ts) / 86400.0 AS handling_days,
       (delivered_ts - pickup_ts) / 86400.0 AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts
WHERE delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
UNION ALL

SELECT 'customer' AS entity_type,
       customer_unique_id AS entity_key,
       approved_ts AS ts,
       0 AS ev_kind,
       approved_ts - 0.0001 AS ev_ts,
       order_id,
       NULL AS is_late, NULL AS days_over, NULL AS handling_days, NULL AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       -- The order's own outcome, carried on its decision row. Read by nothing except the
       -- leave-one-out adjustment in `mode="two_sided_loo"`; the point-in-time builder never
       -- touches these columns, and `_assert_no_outcome_features` keeps them out of the model.
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL THEN 1 ELSE 0 END
           AS own_has_outcome,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS own_is_late,
       COALESCE((pickup_ts - approved_ts) / 86400.0, 0.0)   AS own_handling_days,
       COALESCE((delivered_ts - pickup_ts) / 86400.0, 0.0)  AS own_transit_days,
       COALESCE((delivered_ts - estimated_delivery_ts) / 86400.0, 0.0) AS own_days_over,
       CASE WHEN delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL
                 AND ABS(delivered_ts - approved_ts) <= 2592000.0 THEN 1 ELSE 0 END
           AS own_in_recent
FROM order_facts
UNION ALL

SELECT 'customer' AS entity_type,
       customer_unique_id AS entity_key,
       delivered_ts AS ts,
       1 AS ev_kind,
       delivered_ts AS ev_ts,
       order_id,
       CASE WHEN delivered_ts > estimated_delivery_ts THEN 1 ELSE 0 END AS is_late,
       (delivered_ts - estimated_delivery_ts) / 86400.0 AS days_over,
       (pickup_ts - approved_ts) / 86400.0 AS handling_days,
       (delivered_ts - pickup_ts) / 86400.0 AS transit_days,
       0 AS delta_open,
       0.0 AS open_ts_signed,
       0 AS own_has_outcome, 0 AS own_is_late, 0.0 AS own_handling_days,
       0.0 AS own_transit_days, 0.0 AS own_days_over, 0 AS own_in_recent
FROM order_facts
WHERE delivered_ts IS NOT NULL AND pickup_ts IS NOT NULL;
CREATE INDEX ix_pit_events_key ON pit_events (entity_type, entity_key, ev_ts);

DROP TABLE IF EXISTS feat_seller;
CREATE TABLE feat_seller AS WITH
seller_w AS (
    SELECT order_id,
           ev_kind,
           ts,
           own_has_outcome, own_is_late, own_handling_days, own_transit_days, own_days_over,
           own_in_recent,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wall AS seller_n_prior,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wall AS seller_n_late,
           SUM(CASE WHEN ev_kind = 1 THEN handling_days ELSE 0 END) OVER wall AS seller_sum_handling,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END)  OVER wall AS seller_sum_transit,
           SUM(CASE WHEN ev_kind = 1 THEN days_over ELSE 0 END)     OVER wall AS seller_sum_days_over,
           MAX(CASE WHEN ev_kind = 1 THEN ts END)                  OVER wall AS seller_last_outcome_ts,
           MIN(ts)                                                 OVER wall AS seller_first_ts,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wtrail AS seller_n_prior_recent,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wtrail AS seller_n_late_recent,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END) OVER wtrail AS seller_sum_transit_recent,
           SUM(delta_open) OVER wall AS seller_queue_depth,
           SUM(open_ts_signed) OVER wall AS seller_queue_open_ts_sum
    FROM pit_events
    WHERE entity_type = 'seller'
    WINDOW wall   AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
           wtrail AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN 2592000.0 PRECEDING AND CURRENT ROW)
),
seller_f AS (
    SELECT order_id,
           (seller_n_prior) AS seller_n_prior,
           (seller_n_prior_recent) AS seller_n_prior_recent,
           (seller_n_late + 15.0 * 0.08)
               / (seller_n_prior + 15.0) AS seller_late_rate,
           (seller_n_late_recent + 15.0 * 0.08)
               / (seller_n_prior_recent + 15.0) AS seller_late_rate_recent,
           CASE WHEN (seller_n_prior) > 0
                THEN (seller_sum_handling) / (seller_n_prior) END AS seller_mean_handling,
           CASE WHEN (seller_n_prior) > 0
                THEN (seller_sum_transit) / (seller_n_prior) END AS seller_mean_transit,
           CASE WHEN (seller_n_prior) > 0
                THEN (seller_sum_days_over) / (seller_n_prior) END AS seller_mean_days_over,
           CASE WHEN (seller_n_prior_recent) > 0
                THEN (seller_sum_transit_recent) / (seller_n_prior_recent)
                END AS seller_mean_transit_recent,
           (ts - seller_last_outcome_ts) / 86400.0 AS seller_days_since_outcome,
           (ts - seller_first_ts) / 86400.0        AS seller_history_days,
           seller_queue_depth,
           CASE WHEN seller_queue_depth > 0 THEN (ts - seller_queue_open_ts_sum / seller_queue_depth) / 86400.0 END AS seller_queue_mean_age_days
    FROM seller_w
    WHERE ev_kind = 0
) SELECT * FROM seller_f;
CREATE INDEX ix_feat_seller_order ON feat_seller (order_id);

DROP TABLE IF EXISTS feat_lane;
CREATE TABLE feat_lane AS WITH
lane_w AS (
    SELECT order_id,
           ev_kind,
           ts,
           own_has_outcome, own_is_late, own_handling_days, own_transit_days, own_days_over,
           own_in_recent,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wall AS lane_n_prior,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wall AS lane_n_late,
           SUM(CASE WHEN ev_kind = 1 THEN handling_days ELSE 0 END) OVER wall AS lane_sum_handling,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END)  OVER wall AS lane_sum_transit,
           SUM(CASE WHEN ev_kind = 1 THEN days_over ELSE 0 END)     OVER wall AS lane_sum_days_over,
           MAX(CASE WHEN ev_kind = 1 THEN ts END)                  OVER wall AS lane_last_outcome_ts,
           MIN(ts)                                                 OVER wall AS lane_first_ts,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wtrail AS lane_n_prior_recent,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wtrail AS lane_n_late_recent,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END) OVER wtrail AS lane_sum_transit_recent,
           SUM(delta_open) OVER wall AS lane_queue_depth,
           SUM(open_ts_signed) OVER wall AS lane_queue_open_ts_sum
    FROM pit_events
    WHERE entity_type = 'lane'
    WINDOW wall   AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
           wtrail AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN 2592000.0 PRECEDING AND CURRENT ROW)
),
lane_f AS (
    SELECT order_id,
           (lane_n_prior) AS lane_n_prior,
           (lane_n_prior_recent) AS lane_n_prior_recent,
           (lane_n_late + 15.0 * 0.08)
               / (lane_n_prior + 15.0) AS lane_late_rate,
           (lane_n_late_recent + 15.0 * 0.08)
               / (lane_n_prior_recent + 15.0) AS lane_late_rate_recent,
           CASE WHEN (lane_n_prior) > 0
                THEN (lane_sum_handling) / (lane_n_prior) END AS lane_mean_handling,
           CASE WHEN (lane_n_prior) > 0
                THEN (lane_sum_transit) / (lane_n_prior) END AS lane_mean_transit,
           CASE WHEN (lane_n_prior) > 0
                THEN (lane_sum_days_over) / (lane_n_prior) END AS lane_mean_days_over,
           CASE WHEN (lane_n_prior_recent) > 0
                THEN (lane_sum_transit_recent) / (lane_n_prior_recent)
                END AS lane_mean_transit_recent,
           (ts - lane_last_outcome_ts) / 86400.0 AS lane_days_since_outcome,
           (ts - lane_first_ts) / 86400.0        AS lane_history_days,
           lane_queue_depth,
           CASE WHEN lane_queue_depth > 0 THEN (ts - lane_queue_open_ts_sum / lane_queue_depth) / 86400.0 END AS lane_queue_mean_age_days
    FROM lane_w
    WHERE ev_kind = 0
) SELECT * FROM lane_f;
CREATE INDEX ix_feat_lane_order ON feat_lane (order_id);

DROP TABLE IF EXISTS feat_carrier;
CREATE TABLE feat_carrier AS WITH
carrier_w AS (
    SELECT order_id,
           ev_kind,
           ts,
           own_has_outcome, own_is_late, own_handling_days, own_transit_days, own_days_over,
           own_in_recent,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wall AS carrier_n_prior,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wall AS carrier_n_late,
           SUM(CASE WHEN ev_kind = 1 THEN handling_days ELSE 0 END) OVER wall AS carrier_sum_handling,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END)  OVER wall AS carrier_sum_transit,
           SUM(CASE WHEN ev_kind = 1 THEN days_over ELSE 0 END)     OVER wall AS carrier_sum_days_over,
           MAX(CASE WHEN ev_kind = 1 THEN ts END)                  OVER wall AS carrier_last_outcome_ts,
           MIN(ts)                                                 OVER wall AS carrier_first_ts,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wtrail AS carrier_n_prior_recent,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wtrail AS carrier_n_late_recent,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END) OVER wtrail AS carrier_sum_transit_recent,
           SUM(delta_open) OVER wall AS carrier_queue_depth,
           SUM(open_ts_signed) OVER wall AS carrier_queue_open_ts_sum
    FROM pit_events
    WHERE entity_type = 'carrier'
    WINDOW wall   AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
           wtrail AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN 2592000.0 PRECEDING AND CURRENT ROW)
),
carrier_f AS (
    SELECT order_id,
           (carrier_n_prior) AS carrier_n_prior,
           (carrier_n_prior_recent) AS carrier_n_prior_recent,
           (carrier_n_late + 15.0 * 0.08)
               / (carrier_n_prior + 15.0) AS carrier_late_rate,
           (carrier_n_late_recent + 15.0 * 0.08)
               / (carrier_n_prior_recent + 15.0) AS carrier_late_rate_recent,
           CASE WHEN (carrier_n_prior) > 0
                THEN (carrier_sum_handling) / (carrier_n_prior) END AS carrier_mean_handling,
           CASE WHEN (carrier_n_prior) > 0
                THEN (carrier_sum_transit) / (carrier_n_prior) END AS carrier_mean_transit,
           CASE WHEN (carrier_n_prior) > 0
                THEN (carrier_sum_days_over) / (carrier_n_prior) END AS carrier_mean_days_over,
           CASE WHEN (carrier_n_prior_recent) > 0
                THEN (carrier_sum_transit_recent) / (carrier_n_prior_recent)
                END AS carrier_mean_transit_recent,
           (ts - carrier_last_outcome_ts) / 86400.0 AS carrier_days_since_outcome,
           (ts - carrier_first_ts) / 86400.0        AS carrier_history_days,
           carrier_queue_depth,
           CASE WHEN carrier_queue_depth > 0 THEN (ts - carrier_queue_open_ts_sum / carrier_queue_depth) / 86400.0 END AS carrier_queue_mean_age_days
    FROM carrier_w
    WHERE ev_kind = 0
) SELECT * FROM carrier_f;
CREATE INDEX ix_feat_carrier_order ON feat_carrier (order_id);

DROP TABLE IF EXISTS feat_category;
CREATE TABLE feat_category AS WITH
category_w AS (
    SELECT order_id,
           ev_kind,
           ts,
           own_has_outcome, own_is_late, own_handling_days, own_transit_days, own_days_over,
           own_in_recent,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wall AS category_n_prior,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wall AS category_n_late,
           SUM(CASE WHEN ev_kind = 1 THEN handling_days ELSE 0 END) OVER wall AS category_sum_handling,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END)  OVER wall AS category_sum_transit,
           SUM(CASE WHEN ev_kind = 1 THEN days_over ELSE 0 END)     OVER wall AS category_sum_days_over,
           MAX(CASE WHEN ev_kind = 1 THEN ts END)                  OVER wall AS category_last_outcome_ts,
           MIN(ts)                                                 OVER wall AS category_first_ts,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wtrail AS category_n_prior_recent,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wtrail AS category_n_late_recent,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END) OVER wtrail AS category_sum_transit_recent
    FROM pit_events
    WHERE entity_type = 'category'
    WINDOW wall   AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
           wtrail AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN 2592000.0 PRECEDING AND CURRENT ROW)
),
category_f AS (
    SELECT order_id,
           (category_n_prior) AS category_n_prior,
           (category_n_prior_recent) AS category_n_prior_recent,
           (category_n_late + 15.0 * 0.08)
               / (category_n_prior + 15.0) AS category_late_rate,
           (category_n_late_recent + 15.0 * 0.08)
               / (category_n_prior_recent + 15.0) AS category_late_rate_recent,
           CASE WHEN (category_n_prior) > 0
                THEN (category_sum_handling) / (category_n_prior) END AS category_mean_handling,
           CASE WHEN (category_n_prior) > 0
                THEN (category_sum_transit) / (category_n_prior) END AS category_mean_transit,
           CASE WHEN (category_n_prior) > 0
                THEN (category_sum_days_over) / (category_n_prior) END AS category_mean_days_over,
           CASE WHEN (category_n_prior_recent) > 0
                THEN (category_sum_transit_recent) / (category_n_prior_recent)
                END AS category_mean_transit_recent,
           (ts - category_last_outcome_ts) / 86400.0 AS category_days_since_outcome,
           (ts - category_first_ts) / 86400.0        AS category_history_days
    FROM category_w
    WHERE ev_kind = 0
) SELECT * FROM category_f;
CREATE INDEX ix_feat_category_order ON feat_category (order_id);

DROP TABLE IF EXISTS feat_customer;
CREATE TABLE feat_customer AS WITH
customer_w AS (
    SELECT order_id,
           ev_kind,
           ts,
           own_has_outcome, own_is_late, own_handling_days, own_transit_days, own_days_over,
           own_in_recent,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wall AS customer_n_prior,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wall AS customer_n_late,
           SUM(CASE WHEN ev_kind = 1 THEN handling_days ELSE 0 END) OVER wall AS customer_sum_handling,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END)  OVER wall AS customer_sum_transit,
           SUM(CASE WHEN ev_kind = 1 THEN days_over ELSE 0 END)     OVER wall AS customer_sum_days_over,
           MAX(CASE WHEN ev_kind = 1 THEN ts END)                  OVER wall AS customer_last_outcome_ts,
           MIN(ts)                                                 OVER wall AS customer_first_ts,
           SUM(CASE WHEN ev_kind = 1 THEN 1 ELSE 0 END)            OVER wtrail AS customer_n_prior_recent,
           SUM(CASE WHEN ev_kind = 1 THEN is_late ELSE 0 END)      OVER wtrail AS customer_n_late_recent,
           SUM(CASE WHEN ev_kind = 1 THEN transit_days ELSE 0 END) OVER wtrail AS customer_sum_transit_recent
    FROM pit_events
    WHERE entity_type = 'customer'
    WINDOW wall   AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
           wtrail AS (PARTITION BY entity_key ORDER BY ev_ts RANGE BETWEEN 2592000.0 PRECEDING AND CURRENT ROW)
),
customer_f AS (
    SELECT order_id,
           (customer_n_prior) AS customer_n_prior,
           (customer_n_prior_recent) AS customer_n_prior_recent,
           (customer_n_late + 15.0 * 0.08)
               / (customer_n_prior + 15.0) AS customer_late_rate,
           (customer_n_late_recent + 15.0 * 0.08)
               / (customer_n_prior_recent + 15.0) AS customer_late_rate_recent,
           CASE WHEN (customer_n_prior) > 0
                THEN (customer_sum_handling) / (customer_n_prior) END AS customer_mean_handling,
           CASE WHEN (customer_n_prior) > 0
                THEN (customer_sum_transit) / (customer_n_prior) END AS customer_mean_transit,
           CASE WHEN (customer_n_prior) > 0
                THEN (customer_sum_days_over) / (customer_n_prior) END AS customer_mean_days_over,
           CASE WHEN (customer_n_prior_recent) > 0
                THEN (customer_sum_transit_recent) / (customer_n_prior_recent)
                END AS customer_mean_transit_recent,
           (ts - customer_last_outcome_ts) / 86400.0 AS customer_days_since_outcome,
           (ts - customer_first_ts) / 86400.0        AS customer_history_days
    FROM customer_w
    WHERE ev_kind = 0
) SELECT * FROM customer_f;
CREATE INDEX ix_feat_customer_order ON feat_customer (order_id);


SELECT
    f.order_id,
    f.order_status,
    f.purchase_ts,
    f.approved_ts,
    f.pickup_ts,
    f.delivered_ts,
    f.estimated_delivery_ts,
    f.seller_id,
    f.lane_id,
    f.carrier_id AS carrier_id_key,
    f.customer_unique_id,
    f.expedite_surcharge,
    (f.pickup_ts - f.approved_ts) / 86400.0    AS observed_handling_days,
    (f.delivered_ts - f.pickup_ts) / 86400.0   AS observed_transit_days,
    (f.delivered_ts - f.estimated_delivery_ts) / 86400.0 AS days_over,
    CASE WHEN f.delivered_ts IS NULL THEN NULL
         WHEN f.delivered_ts > f.estimated_delivery_ts THEN 1 ELSE 0 END AS y_late,
    CASE WHEN f.delivered_ts IS NULL OR f.pickup_ts IS NULL THEN NULL
         WHEN f.delivered_ts > f.estimated_delivery_ts
              AND 0.35 + (f.delivered_ts - f.pickup_ts) / 86400.0
                  <= (f.estimated_delivery_ts - f.approved_ts) / 86400.0
         THEN 1 ELSE 0 END AS y_handling_fixable,
    CASE WHEN f.delivered_ts IS NULL OR f.pickup_ts IS NULL THEN NULL
         WHEN f.delivered_ts > f.estimated_delivery_ts
              AND (f.pickup_ts - f.approved_ts) / 86400.0
                  + 0.34 * f.base_transit_days
                  <= (f.estimated_delivery_ts - f.approved_ts) / 86400.0
         THEN 1 ELSE 0 END AS y_transit_fixable,

    (f.estimated_delivery_ts - f.purchase_ts) / 86400.0      AS promise_days,
    (f.estimated_delivery_ts - f.approved_ts) / 86400.0      AS slack_days,
    (f.approved_ts - f.purchase_ts) / 3600.0               AS approval_lag_hours,
    (f.first_shipping_limit_ts - f.approved_ts) / 86400.0    AS handover_deadline_days,
    (f.approved_ts - f.onboarded_ts) / 86400.0               AS seller_tenure_days,
    f.n_items, f.n_sellers, f.n_lanes,
    f.total_price, f.total_freight, f.max_price,
    f.total_freight / (f.total_price + 1.0)                AS freight_ratio,
    f.total_weight_g, f.max_weight_g, f.max_volume_cm3,
    f.n_payment_legs, f.payment_total, f.installments,
    f.distance_km, f.base_transit_days, f.reliability_index, f.daily_capacity,
    (f.estimated_delivery_ts - f.approved_ts) / (86400.0 * f.base_transit_days) AS slack_transit_ratio,
    CASE WHEN f.origin_state = f.dest_state THEN 1 ELSE 0 END AS same_state,
    CAST(f.approved_ts / 86400.0 AS INTEGER) % 7             AS approved_dow,
    CAST(f.approved_ts % 86400.0 / 3600.0 AS INTEGER)        AS approved_hour,
    CASE WHEN CAST(f.approved_ts / 86400.0 AS INTEGER) % 7 IN (5, 6) THEN 1 ELSE 0 END
        AS approved_weekend,
    CAST(CAST(f.purchase_ts / 86400.0 AS INTEGER) % 365 / 7 AS INTEGER) AS purchase_week_of_year,
    f.payment_type, f.service_level, f.fulfilment_mode, f.category,
    f.origin_state, f.dest_state, f.carrier_id
,
    seller_n_prior,
    seller_n_prior_recent,
    seller_late_rate,
    seller_late_rate_recent,
    seller_mean_handling,
    seller_mean_transit,
    seller_mean_days_over,
    seller_mean_transit_recent,
    seller_days_since_outcome,
    seller_history_days,
    seller_queue_depth,
    seller_queue_mean_age_days,
    lane_n_prior,
    lane_n_prior_recent,
    lane_late_rate,
    lane_late_rate_recent,
    lane_mean_handling,
    lane_mean_transit,
    lane_mean_days_over,
    lane_mean_transit_recent,
    lane_days_since_outcome,
    lane_history_days,
    lane_queue_depth,
    lane_queue_mean_age_days,
    carrier_n_prior,
    carrier_n_prior_recent,
    carrier_late_rate,
    carrier_late_rate_recent,
    carrier_mean_handling,
    carrier_mean_transit,
    carrier_mean_days_over,
    carrier_mean_transit_recent,
    carrier_days_since_outcome,
    carrier_history_days,
    carrier_queue_depth,
    carrier_queue_mean_age_days,
    category_n_prior,
    category_n_prior_recent,
    category_late_rate,
    category_late_rate_recent,
    category_mean_handling,
    category_mean_transit,
    category_mean_days_over,
    category_mean_transit_recent,
    category_days_since_outcome,
    category_history_days,
    customer_n_prior,
    customer_n_prior_recent,
    customer_late_rate,
    customer_late_rate_recent,
    customer_mean_handling,
    customer_mean_transit,
    customer_mean_days_over,
    customer_mean_transit_recent,
    customer_days_since_outcome,
    customer_history_days
FROM order_facts f
LEFT JOIN feat_seller ON feat_seller.order_id = f.order_id
LEFT JOIN feat_lane ON feat_lane.order_id = f.order_id
LEFT JOIN feat_carrier ON feat_carrier.order_id = f.order_id
LEFT JOIN feat_category ON feat_category.order_id = f.order_id
LEFT JOIN feat_customer ON feat_customer.order_id = f.order_id
ORDER BY f.approved_ts, f.order_id

