"""Rewrite the committed SQL artefacts in ``sql/`` from the builders.

Run after changing the schema or the feature definitions; ``tests/test_sql_artifacts.py`` fails
until this has been run, so the files in ``sql/`` are always the SQL the code actually executes.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from deliveryrisk.data.schema import schema_ddl  # noqa: E402
from deliveryrisk.features.sql import (  # noqa: E402
    ENTITIES,
    ORDER_FACTS_SQL,
    build_entity_sql,
    build_events_sql,
    build_features_sql,
)

HEADER = [
    "-- Generated by `drisk features configs/headline.yaml --show-sql`. Committed so the feature",
    "-- definitions can be read, reviewed and scheduled without running any Python.",
    "-- Regenerate with `make sql`; tests/test_sql_artifacts.py fails if this file drifts.",
]


def main() -> int:
    out = ROOT / "sql"
    out.mkdir(exist_ok=True)
    for dialect in ("sqlite", "mysql"):
        (out / f"schema_{dialect}.sql").write_text(schema_ddl(dialect))
    parts = [*HEADER, ORDER_FACTS_SQL, build_events_sql(trailing_days=30.0)]
    parts += [
        build_entity_sql(spec, mode="point_in_time", trailing_days=30.0, prior_weight=15.0,
                         prior_rate=0.08)
        for spec in ENTITIES
    ]
    parts.append(build_features_sql(mode="point_in_time"))
    (out / "features_point_in_time.sql").write_text("\n".join(parts) + "\n")
    for p in sorted(out.glob("*.sql")):
        print(f"wrote {p.relative_to(ROOT)} ({p.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
